### ISSUE TITLE
0.2.11 native has unresolved dependencies

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-community/DevILSharp#2]
looks like unresolved dll's sneaked in. maybe this is since building it ourselfs? 
![image](https://user-images.githubusercontent.com/513281/206990845-3cd7a37d-f5ba-4008-ba63-5c37c7d457a0.png)

**Comment by krauthaufen** [comment]
We discussed that about a year ago afaik and iirc the conclusion was something along the lines of: can't really be avoided, so we'll just have to live with it

**Comment by haraldsteinlechner** [comment]
the newest version by @hyazinthh fixes the problem
