### ISSUE TITLE
glib version requirement

### ISSUE THREAD

**Issue by haraldsteinlechner** [aardvark-community/DevILSharp#3]
@hyazinthh where is the linux build from? it requires rather "new" glib?

![image](https://user-images.githubusercontent.com/513281/230570422-3c61d6d1-d215-420e-b0b6-289b0c7ee54c.png)

EDIT: This is the setup:
![image](https://user-images.githubusercontent.com/513281/231096416-caafd0cb-bed3-473f-b79b-42b37e4b14b5.png)

**Comment by hyazinthh** [comment]
Yes, this was built on my personal system (some recent Ubuntu version). We probably should set up a VM with an older OS for all of our Linux builds.

**Comment by krauthaufen** [comment]
Is the github CI old enough?

**Comment by haraldsteinlechner** [comment]
yes, ubuntu 20 is good: https://github.com/actions/runner-images/
all *-latest are problematic.

**Comment by hyazinthh** [comment]
It's probably safe to assume that DevIL does not get anymore releases, so I just rebuilt the binaries in a VM with Ubuntu 20.04 (glibc 2.31).
